#! Makefile
project_dir := ../..

# Module name
MODULE 	:= $(notdir $(shell pwd))

# Source code directory.
SRC_DIR := ./src

# Other include search path, the ./ and ./include is default path
INCLUDE_PATH := 

# Other libary
DEP_LIBS :=

# Other libary search path, the libc libm is default path
DEP_LIBS_PATH :=

# Test source code directory.
TEST_DIR := ./tests

# Test target name
TEST 	:= test_$(MODULE)

include $(project_dir)/scripts/rules.mak
